apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "myriad-db.fullname" . }}
  labels:
    {{- include "myriad-db.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "myriad-db.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "myriad-db.fullname" . }}-headless
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: {{ .Values.volume.storageClassName }}
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.volume.dataSize }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "myriad-db.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "myriad-db.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 10
      volumes:
        - name: {{ include "myriad-db.mongoSecretName" . }}
          secret:
            secretName: {{ include "myriad-db.mongoSecretName" . }}
            items:
              - key: rootUser
                path: MONGO_ROOT_USERNAME
                mode: 0444
              - key: rootPassword
                path: MONGO_ROOT_PASSWORD
                mode: 0444
              - key: userList
                path: MONGO_USERS_LIST
                mode: 0444
        - name: {{ include "myriad-db.mongoKeyConfigMapName" . }}
          configMap:
            name: {{ include "myriad-db.mongoKeyConfigMapName" . }}
            defaultMode: 0755
        - name: {{ include "myriad-db.mongoInitConfigMapName" . }}
          configMap:
            name: {{ include "myriad-db.mongoInitConfigMapName" . }}
            defaultMode: 0755
        - name: {{ include "myriad-db.mongoScriptConfigMapName" . }}
          configMap:
            name: {{ include "myriad-db.mongoScriptConfigMapName" . }}
            defaultMode: 0755
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh","-c"]
          args: ["/home/mongodb/mongo-data-dir-permission.sh && docker-entrypoint.sh mongod --dbpath=/var/lib/mongodb --keyFile=/var/lib/mongoKey/mongo.key --replSet=rs0 --bind_ip=0.0.0.0"]
          env:
            - name: MONGO_DATA_DIR
              value: /var/lib/mongodb
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "myriad-db.mongoSecretName" . }}
                  key: rootUser
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "myriad-db.mongoSecretName" . }}
                  key: rootPassword
            - name: MONGO_USERS_LIST
              valueFrom:
                secretKeyRef:
                  name: {{ include "myriad-db.mongoSecretName" . }}
                  key: userList
          volumeMounts:
            - name: {{ include "myriad-db.mongoSecretName" . }}
              mountPath: /etc/secrets
              readOnly: true
            - name: data
              mountPath: /var/lib/mongodb
            - name: {{ include "myriad-db.mongoKeyConfigMapName" . }}
              mountPath: /var/lib/mongoKeyTemp
            - name: {{ include "myriad-db.mongoInitConfigMapName" . }}
              mountPath: /docker-entrypoint-initdb.d
            - name: {{ include "myriad-db.mongoScriptConfigMapName" . }}
              mountPath: /home/mongodb
          ports:
            - name: mongo
              containerPort: 27017
              protocol: TCP
